# Declare variables to be passed into your templates.

replicaCount: 1

namespace: apnmt

image:
    tag: paymentservice-k8s
    pullPolicy: Always

emissary:
    prefix: /service/payment/

spec:
    ports:
        targetPort: 8084

properties:
    bootsrapServer:
        name: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: my-cluster-kafka-bootstrap.default.svc.cluster.local:9092
