# Declare variables to be passed into your templates.

replicaCount: 1

image:
    tag: paymentservice-k8s
    pullPolicy: Always

emissary:
    prefix: /service/payment/

spec:
    ports:
        targetPort: 8084

properties:
    bootstrapServer:
        name: SPRING_KAFKA_BOOTSTRAPSERVERS
        value: apnmt-kafka-kafka-bootstrap.apnmt.svc.cluster.local:9092
    autoStartup:
        name: SPRING_KAFKA_AUTOSTARTUP
        value: true
    zipkinEnabled:
        name: SPRING_ZIPKIN_ENABLED
        value: true
    zipkinBaseUrl:
        name: SPRING_ZIPKIN_BASEURL
        value: http://jaeger-collector.apnmt.svc.cluster.local:9411
    loggingJsonFormat:
        name: JHIPSTER_LOGGING_USEJSONFORMAT
        value: true
    loggingLogstashEnabled:
        name: JHIPSTER_LOGGING_LOGSTASH_ENABLED
        value: true
    loggingLogstashHost:
        name: JHIPSTER_LOGGING_LOGSTASH_HOST
        value: apnmt-elk-logstash.apnmt.svc.cluster.local
