name: Application CI/CD Production
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pipeline:
    name: paymentservice-k8s pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      NG_CLI_ANALYTICS: false
      GITHUB_USER_REF: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
      GITHUB_TOKEN_REF: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: 'github'
          server-username: GITHUB_USER_REF
          server-password: GITHUB_TOKEN_REF
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          key: apnmt-paymentservice-k8s
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
      - name: Remove SNAPSHOT
        run: |
          mvn versions:set -DremoveSnapshot
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Run tests
        run: |
          chmod +x mvnw
          ./mvnw verify
      - name: Package application
        run: ./mvnw package -Pprod
      - name: Build and publish docker image
        run: |
          ./mvnw -ntp jib:build -Djib.to.image=wittman8/apnmt:paymentservice-k8s-${RELEASE_VERSION} -Djib.to.auth.username="${{ secrets.DOCKER_USERNAME }}" -Djib.to.auth.password="${{ secrets.DOCKER_PASSWORD }}"
      - name: Checkout k8s-config helm chart
        uses: actions/checkout@v2
        with:
          repository: apnmt/k8s-config
          ref: postgres
          path: k8s-config
          token: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
      - name: Combine values.yml
        run: |
          cat src/main/helm/values.yaml >> k8s-config/charts/values.yaml
      - name: Set Helm Chart Name
        uses: datamonsters/replace-action@v2
        with:
          files: 'k8s-config/charts/Chart.yaml'
          replacements: '^CFG:name^=paymentservice-k8s'
      - uses: azure/setup-helm@v1
      - name: Build Helm Chart
        run: |
          mkdir -p repo
          cd repo
          helm dependency update ../k8s-config/charts
          helm package ../k8s-config/charts --app-version ${RELEASE_VERSION} --version ${RELEASE_VERSION}
      - name: Push to repository
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
        with:
          source_file: ./repo/.
          destination_repo: 'apnmt/apnmt-charts'
          user_email: 'tobias.wittmann96@web.de'
          user_name: 'tobi5775'
